### ISSUE TITLE
v1.1.0 progress

### ISSUE THREAD

**Issue by dindinw** [Qitmeer/qng#452]
This is a tracking issue for the **QNG version `v1.1.0 release`** 
- [x] **cleanup the old code**
    - [x] fix the https://github.com/Qitmeer/qng/security/code-scanning/5 on #454  
    - [x] open the new encoding. #458 
- [ ] **memory alloc improvement**
    - [ ] fix the alloc issue on `engine/txscript.parseScriptTemplate` 
    - [ ] fix the alloc issue on `core/types.(*Transaction).decodePrefix`
    - [ ] fix the alloc issue on `core/types.writeTxScriptsToMsgTx`
- [ ] **the CPU profile**   
    - ~~[x] disable the cgo build by default  #456~~
         ```
         2.84s   runtime.cgocall
             github.com/ethereum/go-ethereum/crypto/secp256k1._Cfunc_secp256k1_ext_ecdsa_recover
             github.com/ethereum/go-ethereum/crypto/secp256k1.RecoverPubkey.func1
             github.com/ethereum/go-ethereum/crypto/secp256k1.RecoverPubkey
             github.com/ethereum/go-ethereum/crypto.Ecrecover
             github.com/ethereum/go-ethereum/core/types.recoverPlain
             github.com/ethereum/go-ethereum/core/types.eip2930Signer.Sender
             github.com/ethereum/go-ethereum/core/types.Sender
             github.com/Qitmeer/qng/meerevm/evm.(*VM).validateTx
         ```
         ```
            goos: darwin
            goarch: arm64
            pkg: github.com/ethereum/go-ethereum/crypto
                                   │   cgo.txt    │               nocgo.txt               │
                                   │    sec/op    │    sec/op     vs base                 │
            Sha3-10                 466.9n ±  0%    466.3n ± 0%         ~ (p=0.117 n=10)
            EcrecoverSignature-10   54.24µ ±  1%   154.16µ ± 1%  +184.25% (p=0.000 n=10)
            VerifySignature-10      44.70µ ±  1%   130.03µ ± 1%  +190.89% (p=0.000 n=10)
            DecompressPubkey-10     5.204µ ± 22%   12.319µ ± 0%  +136.73% (p=0.000 n=10)
            geomean                 8.760µ          18.42µ       +110.28%
         ```       
     - [ ] big.nat.make 
         ```
             math/big.nat.make (inline)
             math/big.nat.shl
             math/big.nat.expNNMontgomery
             math/big.nat.expNN
             math/big.(*Int).exp
             math/big.(*Int).Exp (inline)
             github.com/Qitmeer/qng/crypto/ecc/secp256k1.decompressPoint
             github.com/Qitmeer/qng/crypto/ecc/secp256k1.ParsePubKey
             github.com/Qitmeer/qng/crypto/ecc.newSecp256k1DSA.func12
             github.com/Qitmeer/qng/crypto/ecc.secp256k1DSA.ParsePubKey
             github.com/Qitmeer/qng/core/address.NewSecpPubKeyAddress
             github.com/Qitmeer/qng/core/address.NewSecpPubKeyCompressedAddress
             github.com/Qitmeer/qng/engine/txscript.ExtractPkScriptAddrs
             github.com/Qitmeer/qng/consensus/vm.(*VMTx).SetCoinbaseTx
             github.com/Qitmeer/qng/core/blockchain.CheckTransactionSanity
        ```  
- [ ] **the gbt 2.0 API && implementation.**
    - [x] revisit the gbt 2.0 API  
- [ ] **The gbt performance**
    - [ ] empty block && duplicated tx analysis 
         - 37937 [fa28d86595...843fa98961](https://testnet.meerscan.io/block/fa28d86595635e1d8ad794918796441f459a440514fa40f5160abf843fa98961) 1222
        - 37936 [3d36f76885...fe321c024d](https://testnet.meerscan.io/block/3d36f76885171da360d20441fea82280e10dfa065d0be5f08e3b44fe321c024d) 1
        - 37935 [83cda6c5f3...d993b3fc4b](https://testnet.meerscan.io/block/83cda6c5f3e6ed8a28c0495a8cdee3c58959021ea9a511aedea9c4d993b3fc4b) 1222
    - [ ] submit && lock time analysis
        - 4s+ submit time on 1939190 [2c4ed7..181243a](https://meerscan.io/block/2c4ed7541abe858f1f40644049d6e0ceb99584b7ba1caffe3fc701c22181243a)
- [ ] **Integrated the `go-ethereum v1.12`** (https://github.com/ethereum/go-ethereum/releases/tag/v1.12.0)
    - [X] merge v1.12 into https://github.com/Qitmeer/go-ethereum/pull/27/ 
    - [ ]  ethash removed, need to maintain the latest code to the qng code base.  see (https://github.com/ethereum/go-ethereum/pull/27178/)
    - [X] fixed the API changes on the `consensus/consensus.go` #455 
- [ ] **meerpool <-> txpool && performance**
    - [X] the `already known` issue  #453 
    - [X] the rebroadcast issue  #457 
    - [X] local API vs. remote API, might switch back to use `txpool.AddRemote` #457 
        - [X] the `core/txpool/txpool.go:798]  Setting new local account` issue
    - [X] the memory leak in the meerpool  (see https://github.com/ethereum/go-ethereum/issues/23690) https://github.com/ethereum/go-ethereum/pull/27481
        - [X] https://github.com/Qitmeer/go-ethereum/pull/28
        - [X] #473
 - [ ] **the EIP-4844 change, the bobPool and v1.21.1** 
    -  https://eips.ethereum.org/EIPS/eip-4844#blob-transaction
    -  https://github.com/ethereum/go-ethereum/pull/27463
- [ ] **support the performance metrics**
    - [X] introduce the basic metrics code && guide for the InfluxDB && Grafana integration #464 
    - [ ] the mingstats -> the mingstats metrics.    
- [ ] **replace the database layer entirely** 
    - [ ] might be switch to the `pebble` as backend, now it's the default backend. see (https://github.com/ethereum/go-ethereum/pull/27136/)
- [ ] **support the snapshot state for qng**
- [ ] **improved Integrated Tests env**
    - [ ] #164
- [ ] **node Wallet support** 
    - [ ] #353
